// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfikzmfqvwzdphmhjhfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmaWt6bWZxdnd6ZHBobWhqaGZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzQwNDcsImV4cCI6MjA2NTUxMDA0N30.DiM_GAQ-X5rixFuICTNumr_QflkQSi9kA8DYfkDpuWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);